typography_spectrum: 0.3831371625419706
color:
  brandStrength: 0.6466635384131223
  lightness: 0.21751989028416574
  saturation: 0.9560108410660177
  rhythmicContrast: 0.9004983408376575
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.6818328390363604
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8166b88d-8c19-460e-a999-7a03275fe30b.png
name: KeepTrack
navigation:
  - name: Who are we?
    id: c9c17041-7536-445d-bb8a-0cf383376f1e
    type: content
  - name: Features!
    id: bcf3a82a-c4f3-4c25-a9d4-5e8c7b8e6836
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/86f677eb-72b6-496f-b0e2-1581a4ddbb00.png
title: KeepTrack - Fast and Secure Onboarding
description: Speed - Overview - Security
